import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './globals.css'

const comfortaa = Comfortaa({
      preload: true,
      display: 'swap',
      subsets: ['latin'],
      fallback: ['sans-serif'],
      variable: '--font-comfortaa',
      weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
}

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode
}>) {
      return (
            <html
                  lang="en"
                  className={`${comfortaa.variable} h-full antialiased`}
            >
                  <body className="min-h-full flex flex-col">{children}</body>
            </html>
      )
}
